Citizen.CreateThread(function()
    AddTextEntry("r35", "Nissan R35 GTR")
    AddTextEntry("ktmsm", "KTM Supermoto")
    AddTextEntry("04acuratsx", "Acura TSX")
    AddTextEntry("06captivaeu", "Chevy Captiva")
    AddTextEntry("06xc90eu", "Volvo XC90")
    AddTextEntry("323c", "Mazda 323C")
    AddTextEntry("555", "Subaru Impreza Rally")
    AddTextEntry("rmodsupra", "Toyota Supra")
    AddTextEntry("can", "CanAm Maverick X3")
    AddTextEntry("caravan", "Dodge Caravan")
    AddTextEntry("chery", "Chery Tiggo 8")
    AddTextEntry("cubec", "Nissan Cube")
    AddTextEntry("czr2", "Chevy Colorado")
    AddTextEntry("forddriftff3", "Ford Mustang")
    AddTextEntry("fox", "Volkswagon Fox")
    AddTextEntry("frr", "Ford Raptor-Ranger")
    AddTextEntry("gcart", "Golf Cart Extended")
    AddTextEntry("honcrx91", "Honda CR-X")
    AddTextEntry("kcc_kingz_horse", "Harley Davidson Custom")
    AddTextEntry("lexsc300", "Lexus SC300")
    AddTextEntry("mr2zzw30", "Toyota MR2")
    AddTextEntry("ninja300", "Kawasaki Ninja 300")
    AddTextEntry("priusw", "Toyota Prius")
    AddTextEntry("ps13", "Nissan Silvia")
    AddTextEntry("sbus", "Vapid School Bus")
    AddTextEntry("Cherokee", "Jeep Grand Cherokee")
    AddTextEntry("skart", "Shopping go kart")
    AddTextEntry("subarusj", "2021 Subaru WRX")
    AddTextEntry("sulboost", "Turbo Boosted Karin Sultan RS")
    AddTextEntry("svx", "Subaru SVX")
    AddTextEntry("tondar", "Renault Pars Tondar")
    AddTextEntry("touareg", "Volkswagon Touareg")
    AddTextEntry("tritonhpe", "Mitsubishi Triton")
    AddTextEntry("vega", "Chevy Vega")
    AddTextEntry("yaris08", "Toyota Yaris")
    AddTextEntry("lambokart", "Lamborghini Go Kart")
    AddTextEntry("demon", "Dodge Demon")
end)
